new update for workflow

diff --git a/.github/workflows/sync-weblate.yml b/.github/workflows/sync-weblate.yml
--- a/.github/workflows/sync-weblate.yml
+++ b/.github/workflows/sync-weblate.yml
@@ -18,7 +18,7 @@ jobs:
         run: |
           git fetch origin
           COMMITS=$(git log --format=%H --grep="Weblate" origin/main..)
-          echo "::set-output name=commits::$COMMITS"
+          echo "{commits}={$COMMITS}" >> $GITHUB_OUTPUT
 
       - name: Check for Commits in Other Branches
         id: check-other-branches
@@ -26,17 +26,19 @@ jobs:
           OTHER_BRANCHES=$(git branch --format='%(refname:short)' | grep -v "main")
           MISSING_COMMITS=()
           MISSING_BRANCHES=()
-          for BRANCH in $OTHER_BRANCHES; do
-            for COMMIT in ${{ steps.weblate-commits.outputs.commits }}; do
-              if ! git branch --contains $COMMIT | grep -q $BRANCH; then
-                echo "Commit $COMMIT does not exist in branch $BRANCH"
-                MISSING_COMMITS+=($COMMIT)
-                MISSING_BRANCHES+=($BRANCH)
-              fi
-            done
-          done
-          echo "::set-output name=missing_commits::${MISSING_COMMITS[*]}"
-          echo "::set-output name=missing_branches::${MISSING_BRANCHES[*]}"
+
+          while IFS= read -r branch; do
+              while IFS= read -r commit; do
+                  if ! git branch --contains "$commit" | grep -q "$branch"; then
+                      echo "Commit $commit does not exist in branch $branch"
+                      MISSING_COMMITS+=("$commit")
+                      MISSING_BRANCHES+=("$branch")
+                  fi
+              done <<< "$COMMITS"
+          done <<< "$OTHER_BRANCHES"
+          
+          echo "{missing_commits}={MISSING_COMMITS[*]}" >> $GITHUB_OUTPUT
+          echo "{missing_branches}={MISSING_BRANCHES[*]}" >> $GITHUB_OUTPUT
 
       - name: Pull Weblate Commits to Other Branches
         if: steps.check-other-branches.outputs.missing_commits != ''
